const dotenv = require("dotenv");
const fs = require("fs");
const path = require("path");

dotenv.config();

const outDir = path.resolve(process.cwd(), "public");
const outFile = path.join(outDir, "robots.txt");

if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

const disableRobots = process.env.VITE_DISABLE_ROBOTS === "true";

const content = disableRobots
  ? `# robots.txt generated by script
# Crawlers are disallowed
User-agent: *
Disallow: /
`
  : `# robots.txt generated by script
User-agent: *
Allow: /
`;

fs.writeFileSync(outFile, content, "utf8");
console.log(
  `✅ robots.txt generated in /public (disableRobots=${disableRobots})`
);
